### PR TITLE
New syscalls

### PR DESCRIPTION
**Pull request by b-chmiel**

### CODE REVIEW

**Comment by Michcioperz** [comment]
Does the new C++17 test use some new syscalls? I'm asking because if it's meant as a test of whether the new box supports C++17, then I think it misses the point, cause you're only testing the host compiler.

**Comment by Wolf480pl** [comment]
IIRC it's python 3.9 and the gcc it was compiled with that use new syscalls.
Edit: Or maybe we also wanted new gcc? I forgot :/

**Comment by Michcioperz** [comment]
Whichever it is, I'm not seeing how that test helps your goals

**Comment by b-chmiel** [comment]
Yep, you are right about this c++17 test. I wanted to make test that utilises those new syscalls but had no idea for it. I will delete this test to avoid confusion

**Pull request merged**
